//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWebClient.CarRentalService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://sofiazaid.net/carRental/2018/11")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityNotFound", Namespace="http://sofiazaid.net/carRental/2018/11")]
    [System.SerializableAttribute()]
    public partial class EntityNotFound : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateFail", Namespace="http://sofiazaid.net/carRental/2018/11")]
    [System.SerializableAttribute()]
    public partial class UpdateFail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequiredInputOmitted", Namespace="http://sofiazaid.net/carRental/2018/11")]
    [System.SerializableAttribute()]
    public partial class RequiredInputOmitted : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidIdInput", Namespace="http://sofiazaid.net/carRental/2018/11")]
    [System.SerializableAttribute()]
    public partial class InvalidIdInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://sofiazaid.net/carRental/2018/11")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManuFacturingYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Available {
            get {
                return this.AvailableField;
            }
            set {
                if ((this.AvailableField.Equals(value) != true)) {
                    this.AvailableField = value;
                    this.RaisePropertyChanged("Available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarID {
            get {
                return this.CarIDField;
            }
            set {
                if ((this.CarIDField.Equals(value) != true)) {
                    this.CarIDField = value;
                    this.RaisePropertyChanged("CarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ManuFacturing Year")]
        public int ManuFacturingYear {
            get {
                return this.ManuFacturingYearField;
            }
            set {
                if ((this.ManuFacturingYearField.Equals(value) != true)) {
                    this.ManuFacturingYearField = value;
                    this.RaisePropertyChanged("ManuFacturingYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNumber {
            get {
                return this.RegNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RegNumberField, value) != true)) {
                    this.RegNumberField = value;
                    this.RaisePropertyChanged("RegNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://sofiazaid.net/carRental/2018/11")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CarInGarageField;
        
        private CarRentalWebClient.CarRentalService.Car CarToBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        private CarRentalWebClient.CarRentalService.Customer CustomerToBookField;
        
        private System.DateTime EndDateField;
        
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookingID {
            get {
                return this.BookingIDField;
            }
            set {
                if ((this.BookingIDField.Equals(value) != true)) {
                    this.BookingIDField = value;
                    this.RaisePropertyChanged("BookingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarID {
            get {
                return this.CarIDField;
            }
            set {
                if ((this.CarIDField.Equals(value) != true)) {
                    this.CarIDField = value;
                    this.RaisePropertyChanged("CarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CarInGarage {
            get {
                return this.CarInGarageField;
            }
            set {
                if ((this.CarInGarageField.Equals(value) != true)) {
                    this.CarInGarageField = value;
                    this.RaisePropertyChanged("CarInGarage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public CarRentalWebClient.CarRentalService.Car CarToBook {
            get {
                return this.CarToBookField;
            }
            set {
                if ((object.ReferenceEquals(this.CarToBookField, value) != true)) {
                    this.CarToBookField = value;
                    this.RaisePropertyChanged("CarToBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public CarRentalWebClient.CarRentalService.Customer CustomerToBook {
            get {
                return this.CustomerToBookField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerToBookField, value) != true)) {
                    this.CustomerToBookField = value;
                    this.RaisePropertyChanged("CustomerToBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidDateFault", Namespace="http://sofiazaid.net/carRental/2018/11")]
    [System.SerializableAttribute()]
    public partial class InvalidDateFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidOperation", Namespace="http://sofiazaid.net/carRental/2018/11")]
    [System.SerializableAttribute()]
    public partial class InvalidOperation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sofiazaid.net/carRental/2018/11", ConfigurationName="CarRentalService.CustomerService")]
    public interface CustomerService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CustomerService/GetCustomer", ReplyAction="http://sofiazaid.net/carRental/2018/11/CustomerService/GetCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.EntityNotFound), Action="http://sofiazaid.net/carRental/2018/11/CustomerService/GetCustomerEntityNotFoundF" +
            "aultFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="EntityNotFound")]
        CarRentalWebClient.CarRentalService.Customer GetCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CustomerService/GetCustomer", ReplyAction="http://sofiazaid.net/carRental/2018/11/CustomerService/GetCustomerResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Customer> GetCustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://sofiazaid.net/carRental/2018/11/CustomerService/AddNewCustomer", ReplyAction="http://sofiazaid.net/carRental/2018/11/CustomerService/AddNewCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.UpdateFail), Action="http://sofiazaid.net/carRental/2018/11/CustomerService/AddNewCustomerDbUpdateFaul" +
            "tFault", ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Name="UpdateFail")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.RequiredInputOmitted), Action="http://sofiazaid.net/carRental/2018/11/CustomerService/AddNewCustomerRequiredInpu" +
            "tOmittedFaultFault", ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Name="RequiredInputOmitted")]
        int AddNewCustomer(CarRentalWebClient.CarRentalService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://sofiazaid.net/carRental/2018/11/CustomerService/AddNewCustomer", ReplyAction="http://sofiazaid.net/carRental/2018/11/CustomerService/AddNewCustomerResponse")]
        System.Threading.Tasks.Task<int> AddNewCustomerAsync(CarRentalWebClient.CarRentalService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://sofiazaid.net/carRental/2018/11/CustomerService/ChangeCustomer", ReplyAction="http://sofiazaid.net/carRental/2018/11/CustomerService/ChangeCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.UpdateFail), Action="http://sofiazaid.net/carRental/2018/11/CustomerService/ChangeCustomerDbUpdateFaul" +
            "tFault", ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Name="UpdateFail")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.RequiredInputOmitted), Action="http://sofiazaid.net/carRental/2018/11/CustomerService/ChangeCustomerRequiredInpu" +
            "tOmittedFaultFault", ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Name="RequiredInputOmitted")]
        void ChangeCustomer(CarRentalWebClient.CarRentalService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://sofiazaid.net/carRental/2018/11/CustomerService/ChangeCustomer", ReplyAction="http://sofiazaid.net/carRental/2018/11/CustomerService/ChangeCustomerResponse")]
        System.Threading.Tasks.Task ChangeCustomerAsync(CarRentalWebClient.CarRentalService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CustomerService/DeleteCustomer", ReplyAction="http://sofiazaid.net/carRental/2018/11/CustomerService/DeleteCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.InvalidIdInput), Action="http://sofiazaid.net/carRental/2018/11/CustomerService/DeleteCustomerInvalidIdInp" +
            "utFaultFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="InvalidIdInput")]
        void DeleteCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CustomerService/DeleteCustomer", ReplyAction="http://sofiazaid.net/carRental/2018/11/CustomerService/DeleteCustomerResponse")]
        System.Threading.Tasks.Task DeleteCustomerAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceChannel : CarRentalWebClient.CarRentalService.CustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<CarRentalWebClient.CarRentalService.CustomerService>, CarRentalWebClient.CarRentalService.CustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarRentalWebClient.CarRentalService.Customer GetCustomer(int id) {
            return base.Channel.GetCustomer(id);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Customer> GetCustomerAsync(int id) {
            return base.Channel.GetCustomerAsync(id);
        }
        
        public int AddNewCustomer(CarRentalWebClient.CarRentalService.Customer customer) {
            return base.Channel.AddNewCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<int> AddNewCustomerAsync(CarRentalWebClient.CarRentalService.Customer customer) {
            return base.Channel.AddNewCustomerAsync(customer);
        }
        
        public void ChangeCustomer(CarRentalWebClient.CarRentalService.Customer customer) {
            base.Channel.ChangeCustomer(customer);
        }
        
        public System.Threading.Tasks.Task ChangeCustomerAsync(CarRentalWebClient.CarRentalService.Customer customer) {
            return base.Channel.ChangeCustomerAsync(customer);
        }
        
        public void DeleteCustomer(int id) {
            base.Channel.DeleteCustomer(id);
        }
        
        public System.Threading.Tasks.Task DeleteCustomerAsync(int id) {
            return base.Channel.DeleteCustomerAsync(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sofiazaid.net/carRental/2018/11", ConfigurationName="CarRentalService.CarService")]
    public interface CarService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarService/AddCar", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarService/AddCarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.RequiredInputOmitted), Action="http://sofiazaid.net/carRental/2018/11/CarService/AddCarRequiredInputOmittedFault" +
            "Fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="RequiredInputOmitted")]
        int AddCar(CarRentalWebClient.CarRentalService.Car car);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarService/AddCar", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarService/AddCarResponse")]
        System.Threading.Tasks.Task<int> AddCarAsync(CarRentalWebClient.CarRentalService.Car car);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarService/DeleteCar", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarService/DeleteCarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.UpdateFail), Action="http://sofiazaid.net/carRental/2018/11/CarService/DeleteCarDbUpdateFaultFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="UpdateFail")]
        void DeleteCar(int id);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarService/DeleteCar", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarService/DeleteCarResponse")]
        System.Threading.Tasks.Task DeleteCarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarService/GetCarByRegNr", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarService/GetCarByRegNrResponse")]
        CarRentalWebClient.CarRentalService.Car GetCarByRegNr(string regNr);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarService/GetCarByRegNr", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarService/GetCarByRegNrResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car> GetCarByRegNrAsync(string regNr);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarService/GetCarById", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarService/GetCarByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.EntityNotFound), Action="http://sofiazaid.net/carRental/2018/11/CarService/GetCarByIdEntityNotFoundFaultFa" +
            "ult", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="EntityNotFound")]
        CarRentalWebClient.CarRentalService.Car GetCarById(int id);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarService/GetCarById", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarService/GetCarByIdResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car> GetCarByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarService/GetCarInfo", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarService/GetCarInfoResponse")]
        CarRentalWebClient.CarRentalService.CarInfo GetCarInfo(CarRentalWebClient.CarRentalService.CarRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarService/GetCarInfo", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarService/GetCarInfoResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.CarInfo> GetCarInfoAsync(CarRentalWebClient.CarRentalService.CarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarRequestObject", WrapperNamespace="http://sofiazaid.net/carRental/car/2018/11", IsWrapped=true)]
    public partial class CarRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sofiazaid.net/carRental/car/2018/11")]
        public string LicenseKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sofiazaid.net/carRental/car/2018/11", Order=0)]
        public int CarId;
        
        public CarRequest() {
        }
        
        public CarRequest(string LicenseKey, int CarId) {
            this.LicenseKey = LicenseKey;
            this.CarId = CarId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarInfoObject", WrapperNamespace="http://sofiazaid.net/carRental/car/2018/11", IsWrapped=true)]
    public partial class CarInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sofiazaid.net/carRental/car/2018/11", Order=0)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sofiazaid.net/carRental/car/2018/11", Order=1)]
        public string Model;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sofiazaid.net/carRental/car/2018/11", Order=2)]
        public string Brand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sofiazaid.net/carRental/car/2018/11", Order=3)]
        public string RegistrationNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sofiazaid.net/carRental/car/2018/11", Order=4)]
        public int ManufacturingYear;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sofiazaid.net/carRental/car/2018/11", Order=5)]
        public bool Available;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sofiazaid.net/carRental/car/2018/11", Order=6)]
        public bool Deleted;
        
        public CarInfo() {
        }
        
        public CarInfo(int Id, string Model, string Brand, string RegistrationNumber, int ManufacturingYear, bool Available, bool Deleted) {
            this.Id = Id;
            this.Model = Model;
            this.Brand = Brand;
            this.RegistrationNumber = RegistrationNumber;
            this.ManufacturingYear = ManufacturingYear;
            this.Available = Available;
            this.Deleted = Deleted;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarServiceChannel : CarRentalWebClient.CarRentalService.CarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarServiceClient : System.ServiceModel.ClientBase<CarRentalWebClient.CarRentalService.CarService>, CarRentalWebClient.CarRentalService.CarService {
        
        public CarServiceClient() {
        }
        
        public CarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddCar(CarRentalWebClient.CarRentalService.Car car) {
            return base.Channel.AddCar(car);
        }
        
        public System.Threading.Tasks.Task<int> AddCarAsync(CarRentalWebClient.CarRentalService.Car car) {
            return base.Channel.AddCarAsync(car);
        }
        
        public void DeleteCar(int id) {
            base.Channel.DeleteCar(id);
        }
        
        public System.Threading.Tasks.Task DeleteCarAsync(int id) {
            return base.Channel.DeleteCarAsync(id);
        }
        
        public CarRentalWebClient.CarRentalService.Car GetCarByRegNr(string regNr) {
            return base.Channel.GetCarByRegNr(regNr);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car> GetCarByRegNrAsync(string regNr) {
            return base.Channel.GetCarByRegNrAsync(regNr);
        }
        
        public CarRentalWebClient.CarRentalService.Car GetCarById(int id) {
            return base.Channel.GetCarById(id);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car> GetCarByIdAsync(int id) {
            return base.Channel.GetCarByIdAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.CarInfo CarRentalWebClient.CarRentalService.CarService.GetCarInfo(CarRentalWebClient.CarRentalService.CarRequest request) {
            return base.Channel.GetCarInfo(request);
        }
        
        public int GetCarInfo(string LicenseKey, int CarId, out string Model, out string Brand, out string RegistrationNumber, out int ManufacturingYear, out bool Available, out bool Deleted) {
            CarRentalWebClient.CarRentalService.CarRequest inValue = new CarRentalWebClient.CarRentalService.CarRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.CarId = CarId;
            CarRentalWebClient.CarRentalService.CarInfo retVal = ((CarRentalWebClient.CarRentalService.CarService)(this)).GetCarInfo(inValue);
            Model = retVal.Model;
            Brand = retVal.Brand;
            RegistrationNumber = retVal.RegistrationNumber;
            ManufacturingYear = retVal.ManufacturingYear;
            Available = retVal.Available;
            Deleted = retVal.Deleted;
            return retVal.Id;
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.CarInfo> GetCarInfoAsync(CarRentalWebClient.CarRentalService.CarRequest request) {
            return base.Channel.GetCarInfoAsync(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sofiazaid.net/carRental/2018/11", ConfigurationName="CarRentalService.BookingService")]
    public interface BookingService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://sofiazaid.net/carRental/2018/11/BookingService/GetListOfAvailableCars", ReplyAction="http://sofiazaid.net/carRental/2018/11/BookingService/GetListOfAvailableCarsRespo" +
            "nse")]
        CarRentalWebClient.CarRentalService.Car[] GetListOfAvailableCars(System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://sofiazaid.net/carRental/2018/11/BookingService/GetListOfAvailableCars", ReplyAction="http://sofiazaid.net/carRental/2018/11/BookingService/GetListOfAvailableCarsRespo" +
            "nse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car[]> GetListOfAvailableCarsAsync(System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/BookingService/AddBooking", ReplyAction="http://sofiazaid.net/carRental/2018/11/BookingService/AddBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.InvalidDateFault), Action="http://sofiazaid.net/carRental/2018/11/BookingService/AddBookingInvalidDateExcept" +
            "ionFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="InvalidDateFault")]
        int AddBooking(CarRentalWebClient.CarRentalService.Booking booking);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/BookingService/AddBooking", ReplyAction="http://sofiazaid.net/carRental/2018/11/BookingService/AddBookingResponse")]
        System.Threading.Tasks.Task<int> AddBookingAsync(CarRentalWebClient.CarRentalService.Booking booking);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://sofiazaid.net/carRental/2018/11/BookingService/DeleteBooking", ReplyAction="http://sofiazaid.net/carRental/2018/11/BookingService/DeleteBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.InvalidOperation), Action="http://sofiazaid.net/carRental/2018/11/BookingService/DeleteBookingInvalidOperati" +
            "onFaultFault", ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Name="InvalidOperation")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.UpdateFail), Action="http://sofiazaid.net/carRental/2018/11/BookingService/DeleteBookingDbUpdateFaultF" +
            "ault", ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Name="UpdateFail")]
        void DeleteBooking(int id);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://sofiazaid.net/carRental/2018/11/BookingService/DeleteBooking", ReplyAction="http://sofiazaid.net/carRental/2018/11/BookingService/DeleteBookingResponse")]
        System.Threading.Tasks.Task DeleteBookingAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/BookingService/GetBooking", ReplyAction="http://sofiazaid.net/carRental/2018/11/BookingService/GetBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.EntityNotFound), Action="http://sofiazaid.net/carRental/2018/11/BookingService/GetBookingEntityNotFoundFau" +
            "ltFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="EntityNotFound")]
        CarRentalWebClient.CarRentalService.Booking GetBooking(int id);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/BookingService/GetBooking", ReplyAction="http://sofiazaid.net/carRental/2018/11/BookingService/GetBookingResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Booking> GetBookingAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/BookingService/FindBookingsByCustomerEmail" +
            "", ReplyAction="http://sofiazaid.net/carRental/2018/11/BookingService/FindBookingsByCustomerEmail" +
            "Response")]
        CarRentalWebClient.CarRentalService.Booking[] FindBookingsByCustomerEmail(string emailAdress);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/BookingService/FindBookingsByCustomerEmail" +
            "", ReplyAction="http://sofiazaid.net/carRental/2018/11/BookingService/FindBookingsByCustomerEmail" +
            "Response")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Booking[]> FindBookingsByCustomerEmailAsync(string emailAdress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookingServiceChannel : CarRentalWebClient.CarRentalService.BookingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingServiceClient : System.ServiceModel.ClientBase<CarRentalWebClient.CarRentalService.BookingService>, CarRentalWebClient.CarRentalService.BookingService {
        
        public BookingServiceClient() {
        }
        
        public BookingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarRentalWebClient.CarRentalService.Car[] GetListOfAvailableCars(System.DateTime from, System.DateTime to) {
            return base.Channel.GetListOfAvailableCars(from, to);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car[]> GetListOfAvailableCarsAsync(System.DateTime from, System.DateTime to) {
            return base.Channel.GetListOfAvailableCarsAsync(from, to);
        }
        
        public int AddBooking(CarRentalWebClient.CarRentalService.Booking booking) {
            return base.Channel.AddBooking(booking);
        }
        
        public System.Threading.Tasks.Task<int> AddBookingAsync(CarRentalWebClient.CarRentalService.Booking booking) {
            return base.Channel.AddBookingAsync(booking);
        }
        
        public void DeleteBooking(int id) {
            base.Channel.DeleteBooking(id);
        }
        
        public System.Threading.Tasks.Task DeleteBookingAsync(int id) {
            return base.Channel.DeleteBookingAsync(id);
        }
        
        public CarRentalWebClient.CarRentalService.Booking GetBooking(int id) {
            return base.Channel.GetBooking(id);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Booking> GetBookingAsync(int id) {
            return base.Channel.GetBookingAsync(id);
        }
        
        public CarRentalWebClient.CarRentalService.Booking[] FindBookingsByCustomerEmail(string emailAdress) {
            return base.Channel.FindBookingsByCustomerEmail(emailAdress);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Booking[]> FindBookingsByCustomerEmailAsync(string emailAdress) {
            return base.Channel.FindBookingsByCustomerEmailAsync(emailAdress);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sofiazaid.net/carRental/2018/11", ConfigurationName="CarRentalService.CarLeasingService")]
    public interface CarLeasingService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarLeasingService/PickUpReservedCar", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarLeasingService/PickUpReservedCarRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.InvalidOperation), Action="http://sofiazaid.net/carRental/2018/11/CarLeasingService/PickUpReservedCarInvalid" +
            "OperationFaultFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="InvalidOperation")]
        CarRentalWebClient.CarRentalService.Car PickUpReservedCar(int bookingId);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarLeasingService/PickUpReservedCar", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarLeasingService/PickUpReservedCarRespons" +
            "e")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car> PickUpReservedCarAsync(int bookingId);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarLeasingService/DropOffCar", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarLeasingService/DropOffCarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarRentalWebClient.CarRentalService.InvalidOperation), Action="http://sofiazaid.net/carRental/2018/11/CarLeasingService/DropOffCarInvalidOperati" +
            "onFaultFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="InvalidOperation")]
        CarRentalWebClient.CarRentalService.Car DropOffCar(int bookingId);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://sofiazaid.net/carRental/2018/11/CarLeasingService/DropOffCar", ReplyAction="http://sofiazaid.net/carRental/2018/11/CarLeasingService/DropOffCarResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car> DropOffCarAsync(int bookingId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarLeasingServiceChannel : CarRentalWebClient.CarRentalService.CarLeasingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarLeasingServiceClient : System.ServiceModel.ClientBase<CarRentalWebClient.CarRentalService.CarLeasingService>, CarRentalWebClient.CarRentalService.CarLeasingService {
        
        public CarLeasingServiceClient() {
        }
        
        public CarLeasingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarLeasingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarLeasingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarLeasingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarRentalWebClient.CarRentalService.Car PickUpReservedCar(int bookingId) {
            return base.Channel.PickUpReservedCar(bookingId);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car> PickUpReservedCarAsync(int bookingId) {
            return base.Channel.PickUpReservedCarAsync(bookingId);
        }
        
        public CarRentalWebClient.CarRentalService.Car DropOffCar(int bookingId) {
            return base.Channel.DropOffCar(bookingId);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car> DropOffCarAsync(int bookingId) {
            return base.Channel.DropOffCarAsync(bookingId);
        }
    }
}
